Update timestamping.cpp
D:\a\gptp-fork\gptp-fork\src\timestamping.cpp(31,82): error C2440: 'initializing': cannot convert from 'INTERFACE_HARDWARE_TIMESTAMP_CAPABILITIES' to 'INTERFACE_HARDWARE_TIMESTAMP_CAPABILITIES *' [D:\a\gptp-fork\gptp-fork\build\gptp.vcxproj]